# Generated by Django 5.2.1 on 2025-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_pelamar_perteker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perteker',
            name='gender',
            field=models.CharField(choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki'), ('Laki-laki/Perempuan', 'Laki-laki/Perempuan')], default='Laki-laki', max_length=20),
        ),
    ]
