# Generated by Django 5.2.1 on 2025-05-31 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_perteker_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Departemen',
            new_name='departemen',
        ),
    ]
