# Generated by Django 5.2.1 on 2025-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_seleksi_nilai_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleksi',
            name='catatan',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seleksi',
            name='status',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
